format = """
[î‚¶](#c6a0f6)\
$os\
$username\
[î‚°](bg:#ed8796 fg:#c6a0f6)\
$directory\
[î‚°](fg:#ed8796 bg:#f5a97f)\
$git_branch\
$git_status\
[î‚°](fg:#FCA17D bg:#86BBD8)\ 
$c\
$elixir\
$golang\
$java\
$nodejs\
$python\
[î‚°](fg:#7dc4e4 bg:#a6da95)\
$docker_context\
[î‚°](fg:#a6da95 bg:#8aadf4)\
$time\
[î‚° ](fg:#8aadf4)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like ï„   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#c6a0f6 fg:#363a4f"
style_root = "bg:#c6a0f6 fg:#363a4f"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#c6a0f6 fg:#363a4f"
disabled = true                 # Disabled by default

[directory]
style = "bg:#ed8796 fg:#363a4f"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ó°ˆ™ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ó°ˆ™ " = " ó°ˆ™ï„ª "

[c]
symbol = "î˜ "
style = "bg:#7dc4e4 fg:#363a4f"
format = '[ $symbol]($style)'

[python]
symbol = "îœ¼"
style = "bg:#7dc4e4 fg:#363a4f"
format = "[ $symbol ($version) ($virtualenv)]($style)"

[docker_context]
symbol = "ïŒˆ "
style = "bg:#a6da95 fg:#363a4f"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = "î˜­ "
style = "bg:#7dc4e4 fg:#363a4f"
format = '[ $symbol]($style)'

[git_branch]
symbol = "ï˜"
style = "bg:#f5a97f fg:#363a4f"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#f5a97f fg:#363a4f"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "î˜§ "
style = "bg:#7dc4e4 fg:#363a4f"
format = '[ $symbol]($style)'

[java]
symbol = "î‰– "
style = "bg:#7dc4e4 fg:#363a4f"
format = '[ $symbol]($style)'

[nodejs]
symbol = "îœ˜ "
style = "bg:#7dc4e4 fg:#363a4f"
format = '[ $symbol]($style)'

[time]
disabled = false
time_format = "%R"              # Hour:Minute Format
style = "bg:#8aadf4 fg:#363a4f"
format = '[ ğŸ–¤ $time ]($style)'
